### PR TITLE
Handle regex for include / exclude

### PR DESCRIPTION
**Pull request by jethror1**
- switch include and exclude samples to also handle regex patterns
- update default parent instance to `mem1_ssd2_v2_x36` for increased storage

This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_tso500/11)

### CODE REVIEW

**Review by Aisha-D — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_tso500/11)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @jethror1)

___
*[`src/code.sh` line 200 at r1](https://reviewable.io/reviews/eastgenomics/eggd_tso500/11#-NiekYIe6sXf3L4VaUJC:-NiekYIe6sXf3L4VaUJD:b-d93ivf) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/7123e82157b6a52cd0a6976000a884224b405061/src/code.sh#L200)):*
> ```Shell
>     fi
> 
>     # write out new samplesheet with specified rows
> ```

check $sample_rows is not empty, if empty raise error

**Review by jethror1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_tso500/11)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @Aisha-D)

___
*[`src/code.sh` line 200 at r1](https://reviewable.io/reviews/eastgenomics/eggd_tso500/11#-NiekYIe6sXf3L4VaUJC:-Niemk5W472Jnb97WIQG:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/7123e82157b6a52cd0a6976000a884224b405061/src/code.sh#L200)):*
<details><summary><i>Previously, Aisha-D (Aisha) wrote…</i></summary><blockquote>

check $sample_rows is not empty, if empty raise error
</blockquote></details>

Done.

**Review by Aisha-D — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_tso500/11)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jethror1)

**Review by Aisha-D — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_tso500/11)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jethror1)

**Pull request merged**
