### PR TITLE
Updated dnanexus tso500 app with FastQ + demultiplexOnly options

### PR DESCRIPTION
**Pull request by Addy81**
Initial working app.

---
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_tso500/2)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
PR notes about what changes are included would be useful

> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_tso500/2#-:-MgQM1wG63iOeBAoF58d:b-ug2kaq)* status: 2 of 5 files reviewed, 14 unresolved discussions (waiting on @Addy81 and @mattgarner)

___
*[-- commits, line 1 at r3](https://reviewable.io/reviews/eastgenomics/eggd_tso500/2#-MgQTde59b_ldiSl1zNS:-MgQTde59b_ldiSl1zNT:b69jdo) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/c2d5320352a29c9bad2204443e74742c31ad4d8b/-- commits#L1)):*
what is this commits file?
___
*[dxapp.json, line 18 at r3](https://reviewable.io/reviews/eastgenomics/eggd_tso500/2#-MgQMJNS51Tah7lsJ-p1:-MgQMJNS51Tah7lsJ-p2:b-y14lop) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/c2d5320352a29c9bad2204443e74742c31ad4d8b/dxapp.json#L18)):*
> ```JSON
>       "class": "file",
>       "patterns": ["*.zip"],
>       "suggestions": [
> ```

did you fix this? can you just point to the parent dir if not? (i.e. https://github.com/eastgenomics/eggd_athena/blob/4a82a6b15bfae92ec811d8946f074f29e96383ac/dxapp.json#L26)
___
*[dxapp.json, line 38 at r3](https://reviewable.io/reviews/eastgenomics/eggd_tso500/2#-MgQM_qxAZOZy7BrscB0:-MgQM_qxAZOZy7BrscB1:b-mmmg2e) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/c2d5320352a29c9bad2204443e74742c31ad4d8b/dxapp.json#L38)):*
> ```JSON
>       "name": "isNovaSeq",
>       "label": "isNovaSeq",
>       "help": "(Optional) flag to specify NovaSeq data. default= true",
> ```

space on both sides of = or none
___
*[dxapp.json, line 85 at r3](https://reviewable.io/reviews/eastgenomics/eggd_tso500/2#-MgQMwdIBiKz2BtzHBBB:-MgQMwdIBiKz2BtzHBBC:bb730t4) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/c2d5320352a29c9bad2204443e74742c31ad4d8b/dxapp.json#L85)):*
> ```JSON
>       "name": "logs",
>       "label": "logs",
>       "help": "stdout logs from RUO.",
> ```

RUO?
___
*[README.md, line 13 at r3](https://reviewable.io/reviews/eastgenomics/eggd_tso500/2#-MgQNGX4AOQUqpJA3WzN:-MgQNGX4AOQUqpJA3WzO:b-9hd7ax) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/c2d5320352a29c9bad2204443e74742c31ad4d8b/README.md#L13)):*
> ```
> )-
> ```
space
___
*[README.md, line 13 at r3](https://reviewable.io/reviews/eastgenomics/eggd_tso500/2#-MgQNJR023lBnpZq3XA6:-MgQNJR023lBnpZq3XA7:b-4zupo6) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/c2d5320352a29c9bad2204443e74742c31ad4d8b/README.md#L13)):*
> ```
> NextSeq
> ```
only nextseq?
___
*[README.md, line 17 at r3](https://reviewable.io/reviews/eastgenomics/eggd_tso500/2#-MgQNSSNDn7SqfAyE2YT:-MgQNSSNDn7SqfAyE2YU:b-vtlsyn) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/c2d5320352a29c9bad2204443e74742c31ad4d8b/README.md#L17)):*
> ```
> options
> ```
intentionally italicised? 
___
*[src/code.sh, line 16 at r3](https://reviewable.io/reviews/eastgenomics/eggd_tso500/2#-MgQO8XR3HsxTNSKxtl5:-MgQO8XR3HsxTNSKxtl6:boqbvv3) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/c2d5320352a29c9bad2204443e74742c31ad4d8b/src/code.sh#L16)):*
> ```Shell
> 
> # change the owner of the app
> chmod 777 TSO500_ruo/TSO500_RUO_LocalApp/
> ```

does this need to be recursive?
___
*[src/code.sh, line 40 at r3](https://reviewable.io/reviews/eastgenomics/eggd_tso500/2#-MgQRnC47rJqcEFCaO0u:-MgQRnC47rJqcEFCaO0v:bamvaui) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/c2d5320352a29c9bad2204443e74742c31ad4d8b/src/code.sh#L40)):*
> ```Shell
>     
>     cd runfolder
>     # The app requires the fastq files to be present in individual sample folders
> ```

no essential but I think this would look cleaner formatted like:

```
    for fastq_file in *fastq.gz;
    do
        if [[ -e "$fastq_file" ]; then
            # FastQ files expected  in standard naming format i.e. SampleID_S6_L002_R2_001.fastq.gz
            # Substitution below transforms SampleID_S6_L002_R2_001.fastq.gz into SampleID
            samplename=$(echo $fastq_file  | sed 's/_S[0-9]*_L[0-9]*_R[0-9]*_001.fastq.gz//');

```

have 3 lines indented the same looks odd
___
*[src/code.sh, line 47 at r3](https://reviewable.io/reviews/eastgenomics/eggd_tso500/2#-MgQQZTpApXNLrbyMwwY:-MgQQZTpApXNLrbyMwwZ:bhqurbv) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/c2d5320352a29c9bad2204443e74742c31ad4d8b/src/code.sh#L47)):*
> ```Shell
>             # FastQ files expected  in standard naming format i.e. SampleID_S6_L002_R2_001.fastq.gz
>             # Substitution below transforms SampleID_S6_L002_R2_001.fastq.gz into SampleID
>             samplename=$(echo $fastq_file  | sed 's/_S[0-9]*_L[0-9]*_R[0-9]*_001.fastq.gz//'); 
> ```

if you're just wanting to split on first underscore which should be sample name something like this would be simpler:
```
(base) jethro@jethro-T490:~$ fastq_file="mySample_some-rubbsih.fastq"
(base) jethro@jethro-T490:~$ cut -d '_' -f1 <<<"$fastq_file"
mySample

```
___
*[src/code.sh, line 60 at r3](https://reviewable.io/reviews/eastgenomics/eggd_tso500/2#-MgQSSmd1FdNsnu5VtyG:-MgQSSmd1FdNsnu5VtyH:b-mpk9nh) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/c2d5320352a29c9bad2204443e74742c31ad4d8b/src/code.sh#L60)):*
> ```
> FastQs
> ```
FASTQs
___
*[src/code.sh, line 72 at r3](https://reviewable.io/reviews/eastgenomics/eggd_tso500/2#-MgQSc2v1yX4it1o2sX9:-MgQSc2v1yX4it1o2sXA:b-w7l33v) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/c2d5320352a29c9bad2204443e74742c31ad4d8b/src/code.sh#L72)):*
> ```Shell
>         if [[ "${name}" == *.tar.gz ]] || [[ "${name}" == *.tgz ]]; then
>             dx cat "${input_files[${i}]}" | tar zxf - --no-same-owner -C /home/dnanexus/runfolder
> ```

blank line
___
*[src/code.sh, line 109 at r3](https://reviewable.io/reviews/eastgenomics/eggd_tso500/2#-MgQTIOjBqzxbufLxdyx:-MgQTIOjBqzxbufLxdyy:bvawk0k) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/c2d5320352a29c9bad2204443e74742c31ad4d8b/src/code.sh#L109)):*
> ```Shell
> echo "Starting analysis"
> 
> sudo bash TSO500_ruo/TSO500_RUO_LocalApp/TruSight_Oncology_500_RUO.sh \
> ```

does this need to be run as root? If its running the docker image from above thats not best practice, but then I guess this is Illumina so who knows
___
*[src/code.sh, line 114 at r3](https://reviewable.io/reviews/eastgenomics/eggd_tso500/2#-MgQTH3E1FiA-oLn5gS6:-MgQTH3E1FiA-oLn5gS7:b-lxawhv) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/c2d5320352a29c9bad2204443e74742c31ad4d8b/src/code.sh#L114)):*
> ```
>  
> ```
space

**Review by Addy81 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_tso500/2)* status: 2 of 5 files reviewed, 13 unresolved discussions (waiting on @Addy81, @jethror1, and @mattgarner)

___
*[-- commits, line 1 at r3](https://reviewable.io/reviews/eastgenomics/eggd_tso500/2#-MgQTde59b_ldiSl1zNS:-MgQc20N-StyILloge9t:bowbnf6) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/c2d5320352a29c9bad2204443e74742c31ad4d8b/-- commits#L1)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

what is this commits file?
</blockquote></details>

I am not sure where this is?
___
*[dxapp.json, line 18 at r3](https://reviewable.io/reviews/eastgenomics/eggd_tso500/2#-MgQMJNS51Tah7lsJ-p1:-MgQVY_t4hYJYHbOm6BN:b64p5v9) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/c2d5320352a29c9bad2204443e74742c31ad4d8b/dxapp.json#L18)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

did you fix this? can you just point to the parent dir if not? (i.e. https://github.com/eastgenomics/eggd_athena/blob/4a82a6b15bfae92ec811d8946f074f29e96383ac/dxapp.json#L26)
</blockquote></details>

It feels like a dnanexus things no? if it works on the old interface?
___
*[dxapp.json, line 38 at r3](https://reviewable.io/reviews/eastgenomics/eggd_tso500/2#-MgQM_qxAZOZy7BrscB0:-MgQVwgW2dzENTmGjsmL:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/c2d5320352a29c9bad2204443e74742c31ad4d8b/dxapp.json#L38)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

space on both sides of = or none
</blockquote></details>

Done.
___
*[dxapp.json, line 85 at r3](https://reviewable.io/reviews/eastgenomics/eggd_tso500/2#-MgQMwdIBiKz2BtzHBBB:-MgQW9_l4dVFpZQ0VGCm:b9k5jvv) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/c2d5320352a29c9bad2204443e74742c31ad4d8b/dxapp.json#L85)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

RUO?
</blockquote></details>

changed.
___
*[README.md, line 13 at r3](https://reviewable.io/reviews/eastgenomics/eggd_tso500/2#-MgQNJR023lBnpZq3XA6:-MgQWKEh6sVRXCtZcmze:bfvbn1) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/c2d5320352a29c9bad2204443e74742c31ad4d8b/README.md#L13)):*
> -
Yes the TSO500 kit is only available for NextSeqs and NovaSeqs
___
*[src/code.sh, line 16 at r3](https://reviewable.io/reviews/eastgenomics/eggd_tso500/2#-MgQO8XR3HsxTNSKxtl5:-MgQX-d33EWq3HexFiFn:bsudhqx) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/c2d5320352a29c9bad2204443e74742c31ad4d8b/src/code.sh#L16)):*
> intentionally italicised?
It works as it is.
___
*[src/code.sh, line 40 at r3](https://reviewable.io/reviews/eastgenomics/eggd_tso500/2#-MgQRnC47rJqcEFCaO0u:-MgQXDx_5OfayHd1BRpp:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/c2d5320352a29c9bad2204443e74742c31ad4d8b/src/code.sh#L40)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

no essential but I think this would look cleaner formatted like:

```
    for fastq_file in *fastq.gz;
    do
        if [[ -e "$fastq_file" ]; then
            # FastQ files expected  in standard naming format i.e. SampleID_S6_L002_R2_001.fastq.gz
            # Substitution below transforms SampleID_S6_L002_R2_001.fastq.gz into SampleID
            samplename=$(echo $fastq_file  | sed 's/_S[0-9]*_L[0-9]*_R[0-9]*_001.fastq.gz//');

```

have 3 lines indented the same looks odd
</blockquote></details>

Done.
___
*[src/code.sh, line 47 at r3](https://reviewable.io/reviews/eastgenomics/eggd_tso500/2#-MgQQZTpApXNLrbyMwwY:-MgQXFWXBZK2I3xOTmVS:bp3ccbs) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/c2d5320352a29c9bad2204443e74742c31ad4d8b/src/code.sh#L47)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

if you're just wanting to split on first underscore which should be sample name something like this would be simpler:
```
(base) jethro@jethro-T490:~$ fastq_file="mySample_some-rubbsih.fastq"
(base) jethro@jethro-T490:~$ cut -d '_' -f1 <<<"$fastq_file"
mySample

```
</blockquote></details>

There's no naming convention for the samples yet and they add underscores to their names, so this just removes the trailing common suffix
___
*[src/code.sh, line 60 at r3](https://reviewable.io/reviews/eastgenomics/eggd_tso500/2#-MgQSSmd1FdNsnu5VtyG:-MgQXVQTERSOXbfQ-ePO:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/c2d5320352a29c9bad2204443e74742c31ad4d8b/src/code.sh#L60)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

> ```
> FastQs
> ```
FASTQs
</blockquote></details>

Done.
___
*[src/code.sh, line 72 at r3](https://reviewable.io/reviews/eastgenomics/eggd_tso500/2#-MgQSc2v1yX4it1o2sX9:-MgQXeN28M-N3g7Z89N1:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/c2d5320352a29c9bad2204443e74742c31ad4d8b/src/code.sh#L72)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

blank line
</blockquote></details>

Done.
___
*[src/code.sh, line 114 at r3](https://reviewable.io/reviews/eastgenomics/eggd_tso500/2#-MgQTH3E1FiA-oLn5gS6:-MgQYBasEFviI2LtRvrO:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/c2d5320352a29c9bad2204443e74742c31ad4d8b/src/code.sh#L114)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

> ```
>  
> ```
space
</blockquote></details>

Done.

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_tso500/2)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @Addy81 and @mattgarner)

___
*[dxapp.json, line 18 at r3](https://reviewable.io/reviews/eastgenomics/eggd_tso500/2#-MgQMJNS51Tah7lsJ-p1:-MgQdiJM6_uXww4E9G1M:b-uw8iwr) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/c2d5320352a29c9bad2204443e74742c31ad4d8b/dxapp.json#L18)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

It feels like a dnanexus things no? if it works on the old interface?
</blockquote></details>

I guess, maybe add both as suggestions and they might fix it in the future? or just leave it ¯\_(ツ)_/¯

**Review by jethror1 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_tso500/2#-:-MgQlV6wCZEXuhw8Fc-C:bnfp4nl)* status: 2 of 5 files reviewed, all discussions resolved (waiting on @mattgarner)

**Review by jethror1 — APPROVED** [review]
> Reviewed 2 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_tso500/2)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Addy81)

**Pull request merged**
